workers_dev = true
name = "rozemyne"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[routes]]
pattern = "preview.kagami.moe"
custom_domain = true
