name: Sanity Checks
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  sanity:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
      - name: Install dependencies
        run: |
          npm install -g corepack@latest
          corepack pnpm install
      - name: Linting
        run: corepack pnpm lint
      - name: Typechecking
        run: corepack pnpm typecheck
      - name: Build
        run: corepack pnpm build
